apiVersion: v1
kind: Service
metadata:
  name: simple-app-node-port
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31515
  selector:
    component: simple-app
